### ISSUE TITLE
Allow iter_ts to iterate over given list of gpis

### ISSUE THREAD

**Issue by IsabellaP** [TUW-GEO/pygeobase#10]
This would allow easy subsetting for time series of interest.

Could also be implemented as a slicing operation on the dataset.

**Comment by sebhahn** [comment]
I thought this is supported by defining a (sub-)grid only with points of interest?

**Comment by cpaulik** [comment]
Yes that is what I meant by the second option.

We should support a special slicing operation on the Dataset object that returns a new Dataset object defined on the spatial subset that is requested. Behind the scenes we can slice the grid and return a new dataset object with this new grid.
