### ISSUE TITLE
No reading in append mode?

### ISSUE THREAD

**Issue by cpaulik** [TUW-GEO/pygeobase#18]
Is there a reason for now allowing reading in append mode?

NetCDF4 is allowing it. From the [netCDF4 documentation](http://unidata.github.io/netcdf4-python/#netCDF4.Dataset):

> a and r+ mean append (in analogy with serial files); an existing file is opened for reading and writing.

**Comment by sebhahn** [comment]
It is not supported by e.g. pygenio at the moment. 

If we support it, this means the permission of the read and write operation needs to be checked at the i/o class level.

**Comment by cpaulik** [comment]
I just ran into this again. I think we have to support reading in append mode. Otherwise this makes a lot of applications impossible.
