### ISSUE TITLE
Check on documentation of write(..)

### ISSUE THREAD

**Issue by doroko** [TUW-GEO/pygeobase#22]
write function in io_base.py, class GriddedBase(object) ~l.394

**Comment by cpaulik** [comment]
What exactly do you mean?

The documentation of the [write function of the GriddedBase object](https://github.com/TUW-GEO/pygeobase/blob/master/pygeobase/io_base.py#L438) could be expanded if that is what you mean.

**Comment by cpaulik** [comment]
The writing function documentation is copy pasted from the read documentation. So that should be fixed.

**Comment by cpaulik** [comment]
Fixed in https://github.com/TUW-GEO/pygeobase/commit/13e2479197e95c66b17637f1923f19391dfb7208
