### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by alegrub88** [TUW-GEO/pygeobase#38]
I had troubles with the installation, which were solved by updating the requirements in the setup.py from:
'pyscaffold>=2.4rc1,<2.5a0'
to
'pyscaffold>=2.5a0,<2.6a0'

The error message was something like "no packages or working download links found for pyscaffold<2.5a0,2.4rc1"

**Comment by cpaulik** [comment]
How did you try to install it? I just tried `pip install pygeobase` and it worked without problems.

**Comment by alegrub88** [comment]
I think it was git clone and python setup.py develop... I had similar issues with several of the packages on the GEO git too.

**Comment by cpaulik** [comment]
Do you have any configuration for the internal pip server? I just had a similar problem which was solved by updating my `.pydistutils.cfg` and `pip.conf` to point to `dvlp1.geo.tuwien.ac.at` instead of `dvlp1.ipf.tuwien.ac.at`

**Comment by alegrub88** [comment]
Yes, I had the configuration but I already switched it to the geo domain though this didn't work for me for whatever reason but I had no time to try fix it. I therefore removed the configuration for the internal pip server again to be able to install packages... But to be honest, I cannot remember whether I removed it before or after the above mentioned error message occured.... Since I thought the problem was an old pyscaffold version requirement in the setup file I didn't pay attention any more.

**Comment by cpaulik** [comment]
This was a problem unrelated to pygeobase.

**Comment by sebhahn** [comment]
@cpaulik I get the same error for almost every package (pygeobase, pytesmo, pygeogrids)

using e.g. pip install -e git+git@github.com:TUW-GEO/pygeobase.git@v0.3.11#egg=pygeobase

**Comment by sebhahn** [comment]
I think it might be related to `~/.pydistutils.cfg`, removing the file helps, but I'm not sure why it suddenly creates these problems

**Comment by cpaulik** [comment]
Does a normal install still work? For editable installs the problem might be that distutils can not handle the internal pip server and the official one. It seems to be using easy install which is quite old. For development it might be a good practice to install pyscaffold first.

**Comment by sebhahn** [comment]
At the moment I'm not using `~/.pydistutils.cfg` and everything is fine
